// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "FAKE_aws_content_delivery_bucket",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://fake.cloudfront.net",
    "aws_cognito_identity_pool_id": "eu-central-1:FAKE",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_FAKE",
    "aws_user_pools_web_client_id": "FAKE",
    "oauth": {
        "domain": "FAKE.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://example.com/callback/",
        "redirectSignOut": "https://example.com/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
